// generated by stringer -type=Type; DO NOT EDIT

package packet

import "fmt"

const (
	_Type_name_0 = "JoinServerRequestTypeJoinServerAcceptTypeJoinServerRefuseType"
	_Type_name_1 = "UdpConnectionEstablishedTypeEnterGamePermissionTypeEnteredGameNotificationType"
	_Type_name_2 = "PingTypePongTypePungType"
	_Type_name_3 = "LoadLevelTypeCurrentPlayersInfoType"
	_Type_name_4 = "LocalPlayerInfoType"
	_Type_name_5 = "HandshakeType"
	_Type_name_6 = "TimeRequestTypeTimeResponseType"
)

var (
	_Type_index_0 = [...]uint8{0, 21, 41, 61}
	_Type_index_1 = [...]uint8{0, 28, 51, 78}
	_Type_index_2 = [...]uint8{0, 8, 16, 24}
	_Type_index_3 = [...]uint8{0, 13, 35}
	_Type_index_4 = [...]uint8{0, 19}
	_Type_index_5 = [...]uint8{0, 13}
	_Type_index_6 = [...]uint8{0, 15, 31}
)

func (i Type) String() string {
	switch {
	case 1 <= i && i <= 3:
		i -= 1
		return _Type_name_0[_Type_index_0[i]:_Type_index_0[i+1]]
	case 5 <= i && i <= 7:
		i -= 5
		return _Type_name_1[_Type_index_1[i]:_Type_index_1[i+1]]
	case 10 <= i && i <= 12:
		i -= 10
		return _Type_name_2[_Type_index_2[i]:_Type_index_2[i+1]]
	case 20 <= i && i <= 21:
		i -= 20
		return _Type_name_3[_Type_index_3[i]:_Type_index_3[i+1]]
	case i == 30:
		return _Type_name_4
	case i == 100:
		return _Type_name_5
	case 105 <= i && i <= 106:
		i -= 105
		return _Type_name_6[_Type_index_6[i]:_Type_index_6[i+1]]
	default:
		return fmt.Sprintf("Type(%d)", i)
	}
}
